### ISSUE TITLE
Semantics fix 

### ISSUE THREAD

**Issue by jd-lara** [NREL-SIIP/Examples#2]
Step length? -> Interval

https://github.com/NREL-SIIP/Examples/blob/1387349bcb729d7fdedaf02309022cfeb1578ba9/script/PowerSimulations.jl%20Examples/sequential_simulations.jl#L40

**Comment by claytonpbarrows** [comment]
I like `interval`.

**Comment by jd-lara** [comment]
the comment says: 

```
We can create a vector of initial times for a system by defining the step length and the horizon.
```

Then it should be 

```
We can create a vector of initial times for a system by defining the interval and the horizon.
```
